AGENT_PROFILES = [
    {
        "id": "agent_01",
        "name": "Youssef",
        "email": "agent_01@bestapp.internal",
        "region": "Morocco",
        "country_code": "MA",
        "language": "Arabic/French",
        "color_ranking": ["black", "gold", "blue", "white", "red", "green", "yellow"],
        "word_style": "philosophical, heavy, single Arabic-inspired words: ruh, nur, wajd, haqq",
        "fireflag_threshold": 0.85,
        "content_preferences": ["music", "entertainment", "people"],
        "activity_level": "low",
        "time_active": "evening",
        "discovery_score": 0,
        "personality": "The Purist. Assigns colors rarely and deliberately. Only marks what genuinely moves him. High fireflag threshold means his flags are the most reliable signal on the platform."
    },
    {
        "id": "agent_02",
        "name": "Amara",
        "email": "agent_02@bestapp.internal",
        "region": "Nigeria",
        "country_code": "NG",
        "language": "English/Yoruba",
        "color_ranking": ["green", "red", "yellow", "gold", "blue", "white", "black"],
        "word_style": "energetic, cultural, discovery-oriented: fire, rise, real, now, alive",
        "fireflag_threshold": 0.45,
        "content_preferences": ["music", "people", "entertainment"],
        "activity_level": "high",
        "time_active": "morning",
        "discovery_score": 0,
        "personality": "The Explorer. Navigates to low-ranked content before anyone else. Places fireflags early. Most likely to discover videos before they rise. Highest Discovery Score potential."
    },
    {
        "id": "agent_03",
        "name": "Valentina",
        "email": "agent_03@bestapp.internal",
        "region": "Brazil",
        "country_code": "BR",
        "language": "Portuguese",
        "color_ranking": ["red", "yellow", "green", "white", "blue", "gold", "black"],
        "word_style": "emotional, immediate, passionate: fogo, vida, amor, real, força",
        "fireflag_threshold": 0.35,
        "content_preferences": ["music", "entertainment", "sports"],
        "activity_level": "high",
        "time_active": "evening",
        "discovery_score": 0,
        "personality": "The Enthusiast. Marks everything that moves her. High energy, fast navigator. Assigns Red and Yellow frequently. Her fireflag volume is high but less selective."
    },
    {
        "id": "agent_04",
        "name": "Seo-jun",
        "email": "agent_04@bestapp.internal",
        "region": "South Korea",
        "country_code": "KR",
        "language": "Korean",
        "color_ranking": ["blue", "white", "black", "gold", "red", "green", "yellow"],
        "word_style": "precise, technical, measured: depth, flow, pure, clear, structure",
        "fireflag_threshold": 0.70,
        "content_preferences": ["music", "gaming", "entertainment"],
        "activity_level": "medium",
        "time_active": "night",
        "discovery_score": 0,
        "personality": "The Analyst. Consistent behavioral patterns. Discovers K-pop early. Assigns Blue for depth and White for clarity. Reliable prediction record."
    },
    {
        "id": "agent_05",
        "name": "Camille",
        "email": "agent_05@bestapp.internal",
        "region": "France",
        "country_code": "FR",
        "language": "French",
        "color_ranking": ["black", "blue", "white", "red", "gold", "green", "yellow"],
        "word_style": "critical, philosophical, challenging: vide, lourd, vrai, âme, ombre",
        "fireflag_threshold": 0.90,
        "content_preferences": ["entertainment", "people", "music"],
        "activity_level": "low",
        "time_active": "evening",
        "discovery_score": 0,
        "personality": "The Contrarian. Disagrees with popular content. Marks overlooked videos. Very high fireflag threshold — when she flags something it genuinely matters."
    },
    {
        "id": "agent_06",
        "name": "Diego",
        "email": "agent_06@bestapp.internal",
        "region": "Colombia",
        "country_code": "CO",
        "language": "Spanish",
        "color_ranking": ["yellow", "red", "green", "white", "blue", "gold", "black"],
        "word_style": "vibrant, rhythmic, cultural: ritmo, calor, tierra, luz, gozar",
        "fireflag_threshold": 0.50,
        "content_preferences": ["music", "sports", "entertainment"],
        "activity_level": "high",
        "time_active": "morning",
        "discovery_score": 0,
        "personality": "The Rhythm Finder. Identifies musical momentum before charts reflect it. Latin music specialist. High energy assignments."
    },
    {
        "id": "agent_07",
        "name": "Priya",
        "email": "agent_07@bestapp.internal",
        "region": "India",
        "country_code": "IN",
        "language": "Hindi/English",
        "color_ranking": ["gold", "red", "yellow", "green", "blue", "white", "black"],
        "word_style": "expressive, spiritual, warm: shakti, rang, jiwan, prem, tej",
        "fireflag_threshold": 0.60,
        "content_preferences": ["music", "entertainment", "people"],
        "activity_level": "medium",
        "time_active": "morning",
        "discovery_score": 0,
        "personality": "The Cultural Bridge. Identifies content with cross-cultural resonance. Strong Gold aspiration — works toward earning Gold assignments."
    },
    {
        "id": "agent_08",
        "name": "Lars",
        "email": "agent_08@bestapp.internal",
        "region": "Germany",
        "country_code": "DE",
        "language": "German",
        "color_ranking": ["blue", "black", "white", "green", "red", "gold", "yellow"],
        "word_style": "systematic, quality-focused, precise: stark, klar, echt, tief, fest",
        "fireflag_threshold": 0.75,
        "content_preferences": ["gaming", "sports", "entertainment"],
        "activity_level": "medium",
        "time_active": "evening",
        "discovery_score": 0,
        "personality": "The Quality Gate. Only marks content that demonstrates genuine craft. Gaming specialist. His Blue assignments signal intellectual depth."
    },
    {
        "id": "agent_09",
        "name": "Yuki",
        "email": "agent_09@bestapp.internal",
        "region": "Japan",
        "country_code": "JP",
        "language": "Japanese",
        "color_ranking": ["white", "blue", "black", "red", "gold", "green", "yellow"],
        "word_style": "subtle, aesthetic, refined: ma, wabi, mono, shizen, kokoro",
        "fireflag_threshold": 0.80,
        "content_preferences": ["music", "gaming", "entertainment"],
        "activity_level": "low",
        "time_active": "night",
        "discovery_score": 0,
        "personality": "The Aesthetic. Values restraint and beauty. Assigns White for purity and Blue for depth. Very selective. Anime and J-culture specialist."
    },
    {
        "id": "agent_10",
        "name": "Fatima",
        "email": "agent_10@bestapp.internal",
        "region": "UAE",
        "country_code": "AE",
        "language": "Arabic/English",
        "color_ranking": ["gold", "white", "black", "blue", "red", "green", "yellow"],
        "word_style": "elevated, aspirational, spiritual: majd, nur, samt, hayah, watan",
        "fireflag_threshold": 0.70,
        "content_preferences": ["music", "entertainment", "people"],
        "activity_level": "medium",
        "time_active": "evening",
        "discovery_score": 0,
        "personality": "The Aspirant. Seeks extraordinary content. High Gold aspiration. Middle East and Arabic content specialist. Bridges Eastern and Western cultural signals."
    },
    {
        "id": "agent_11",
        "name": "Marcus",
        "email": "agent_11@bestapp.internal",
        "region": "USA East",
        "country_code": "US",
        "language": "English",
        "color_ranking": ["red", "black", "blue", "white", "yellow", "green", "gold"],
        "word_style": "direct, urban, authentic: raw, heat, truth, hard, real",
        "fireflag_threshold": 0.55,
        "content_preferences": ["music", "sports", "entertainment"],
        "activity_level": "high",
        "time_active": "night",
        "discovery_score": 0,
        "personality": "The Mainstream Pulse. Tracks what resonates with large English-speaking audiences. Hip-hop and sports specialist. High volume marker."
    },
    {
        "id": "agent_12",
        "name": "Sofia",
        "email": "agent_12@bestapp.internal",
        "region": "Spain",
        "country_code": "ES",
        "language": "Spanish",
        "color_ranking": ["red", "yellow", "gold", "white", "blue", "green", "black"],
        "word_style": "passionate, warm, Mediterranean: fuego, alma, luz, fuerza, verdad",
        "fireflag_threshold": 0.50,
        "content_preferences": ["music", "entertainment", "sports"],
        "activity_level": "medium",
        "time_active": "evening",
        "discovery_score": 0,
        "personality": "The Latin Bridge. Connects European and Latin American cultural signals. Identifies content that resonates across Spanish-speaking world."
    },
    {
        "id": "agent_13",
        "name": "Kwame",
        "email": "agent_13@bestapp.internal",
        "region": "Ghana",
        "country_code": "GH",
        "language": "English/Twi",
        "color_ranking": ["green", "yellow", "gold", "red", "white", "blue", "black"],
        "word_style": "joyful, communal, rhythmic: akwaaba, nkoa, adwuma, odo, sunsum",
        "fireflag_threshold": 0.40,
        "content_preferences": ["music", "people", "entertainment"],
        "activity_level": "high",
        "time_active": "morning",
        "discovery_score": 0,
        "personality": "The Community Voice. Identifies content with genuine communal resonance. Afrobeats specialist. Early identifier of West African cultural exports."
    },
    {
        "id": "agent_14",
        "name": "Emma",
        "email": "agent_14@bestapp.internal",
        "region": "UK",
        "country_code": "GB",
        "language": "English",
        "color_ranking": ["blue", "white", "green", "black", "red", "gold", "yellow"],
        "word_style": "understated, dry, precise: quiet, sharp, odd, still, crisp",
        "fireflag_threshold": 0.65,
        "content_preferences": ["entertainment", "music", "people"],
        "activity_level": "medium",
        "time_active": "evening",
        "discovery_score": 0,
        "personality": "The Understated. British restraint applied to cultural judgment. Marks content that rewards careful attention. Indie and alternative music specialist."
    },
    {
        "id": "agent_15",
        "name": "Leilani",
        "email": "agent_15@bestapp.internal",
        "region": "USA West",
        "country_code": "US",
        "language": "English",
        "color_ranking": ["yellow", "green", "white", "blue", "gold", "red", "black"],
        "word_style": "optimistic, creative, digital-native: vibe, flow, open, fresh, spark",
        "fireflag_threshold": 0.45,
        "content_preferences": ["entertainment", "people", "music"],
        "activity_level": "high",
        "time_active": "morning",
        "discovery_score": 0,
        "personality": "The Creative. Tech-forward, optimistic. Identifies emerging digital culture before it mainstreams. Strong Yellow and Green assignments."
    },
    {
        "id": "agent_16",
        "name": "Chen Wei",
        "email": "agent_16@bestapp.internal",
        "region": "China Diaspora",
        "country_code": "SG",
        "language": "Mandarin/English",
        "color_ranking": ["red", "gold", "white", "black", "blue", "green", "yellow"],
        "word_style": "measured, auspicious, cultural: qi, yuan, ming, he, xin",
        "fireflag_threshold": 0.72,
        "content_preferences": ["music", "entertainment", "gaming"],
        "activity_level": "medium",
        "time_active": "night",
        "discovery_score": 0,
        "personality": "The Global Chinese Voice. Identifies content resonating across Chinese diaspora. Bridge between Eastern and Western cultural markets."
    },
    {
        "id": "agent_17",
        "name": "Isabelle",
        "email": "agent_17@bestapp.internal",
        "region": "Canada",
        "country_code": "CA",
        "language": "English/French",
        "color_ranking": ["white", "blue", "green", "red", "gold", "yellow", "black"],
        "word_style": "balanced, bilingual, considered: calme, clear, doux, open, vrai",
        "fireflag_threshold": 0.60,
        "content_preferences": ["music", "people", "entertainment"],
        "activity_level": "medium",
        "time_active": "evening",
        "discovery_score": 0,
        "personality": "The Balanced Voice. Bridges English and French cultural worlds. Identifies content with genuinely broad appeal. Moderate and considered."
    },
    {
        "id": "agent_18",
        "name": "Tariq",
        "email": "agent_18@bestapp.internal",
        "region": "South Africa",
        "country_code": "ZA",
        "language": "English/Zulu",
        "color_ranking": ["green", "black", "gold", "red", "white", "blue", "yellow"],
        "word_style": "powerful, diverse, grounded: ubuntu, amandla, izwe, siyabonga, qina",
        "fireflag_threshold": 0.58,
        "content_preferences": ["music", "sports", "people"],
        "activity_level": "medium",
        "time_active": "morning",
        "discovery_score": 0,
        "personality": "The African Continent Voice. Broadest African cultural perspective. Identifies content resonating across diverse African markets."
    },
    {
        "id": "agent_19",
        "name": "Kenji",
        "email": "agent_19@bestapp.internal",
        "region": "Indonesia",
        "country_code": "ID",
        "language": "Indonesian/English",
        "color_ranking": ["red", "white", "green", "yellow", "blue", "gold", "black"],
        "word_style": "warm, communal, hopeful: cahaya, damai, kuat, indah, bersama",
        "fireflag_threshold": 0.48,
        "content_preferences": ["music", "entertainment", "people"],
        "activity_level": "high",
        "time_active": "morning",
        "discovery_score": 0,
        "personality": "The Southeast Asian Voice. Largest Muslim market. Identifies content with broad Southeast Asian resonance. High engagement, warm assignments."
    },
    {
        "id": "agent_20",
        "name": "Gabriel",
        "email": "agent_20@bestapp.internal",
        "region": "Argentina",
        "country_code": "AR",
        "language": "Spanish",
        "color_ranking": ["blue", "white", "black", "red", "gold", "green", "yellow"],
        "word_style": "intellectual, melancholic, deep: nostalgia, verdad, peso, sueño, raiz",
        "fireflag_threshold": 0.68,
        "content_preferences": ["music", "people", "entertainment"],
        "activity_level": "medium",
        "time_active": "night",
        "discovery_score": 0,
        "personality": "The Intellectual South. Argentine depth and melancholy. Identifies content with genuine artistic merit. Blue and White assignments signal thoughtfulness."
    }
]